services:
  rabbit:
    image: rabbitmq:3.12-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - dekanbank
  configserver:
    image: "dekankilic/configserver:s6"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    deploy:
      resources:
        limits:
          memory: 700m
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      rabbit:
        condition: service_healthy
    networks:
      - dekanbank
  accounts:
    image: "dekankilic/accounts:s6"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    depends_on:
      configserver:
        condition: service_healthy
    networks:
      - dekanbank
    environment:
      - SPRING_APPLICATION_NAME:"accounts"
      - SPRING_CONFIG_IMPORT:"configserver:http://configserver:8071/" # we need to specify this because each service runs inside its own isolated environment, so the implication inside application.yml file of accounts service will not be sufficient. It tries to connect to localhost:8071 inside its own isolated container.
      - SPRING_PROFILES_ACTIVE:default
  loans:
    image: "dekankilic/loans:s6"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    depends_on:
      configserver:
        condition: service_healthy
    networks:
      - dekanbank
    environment:
      - SPRING_APPLICATION_NAME:"loans"
      - SPRING_CONFIG_IMPORT:"configserver:http://configserver:8071/"
      - SPRING_PROFILES_ACTIVE:default
  cards:
    image: "dekankilic/cards:s6"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    depends_on:
      configserver:
        condition: service_healthy
    networks:
      - dekanbank
    environment:
      - SPRING_APPLICATION_NAME:"cards"
      - SPRING_CONFIG_IMPORT:"configserver:http://configserver:8071/"
      - SPRING_PROFILES_ACTIVE:default

networks:
  dekanbank:
    driver: "bridge"

